DATA_FILE_PATH = "/home/data"
CROP_LABELS = ['maize','groundnut', 'rice', 'soya bean', 'sorghum', 'yam', 'sesame', 'beans', 'sunflower', 'chick peas', 'wheat', 'other']
SPLITS = ['train', 'val', 'test']
NON_DL_MODELS = ['logreg', 'random_forest']
DL_MODELS = ['bidir_clstm','fcn']
S1_NUM_BANDS = 2
S2_NUM_BANDS = 10
GRID_SIZE = 64
#MIN_TIMESTAMPS = 25
MIN_TIMESTAMPS = 2
